[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings=[
    '@ds-test/=lib/forge-std/lib/ds-test/src/',
    '@forge-std/=lib/forge-std/src/',
    '@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    '@src/=src/',
    '@test/=test/'
]


[fuzz]
runs = 256

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config